name: "QuickMudra.in"
brand_name: "QuickMudra"
description: "Quick Loans, Insurance, Mutual Funds and Accounting"

email: "support@quickmudra.in"
phone: "+91-0000000000"
address: ""

facebook: "http://facebook.com/"
twitter: "http://twitter.com/"

url: "https://quickmudra.in"

permalink: /:title/