name: "QuickMudra.in"
brand_name: "QuickMudra"
description: "Quick Loans, Credit Cards & Insurance in Lucknow"

email: "support@quickmudra.in"
phone: "+910000000000"
address: ""

facebook: "http://facebook.com/jassithedude"
twitter: "http://twitter.com/itsjaswinder"

url: "https://quickmudra.in"

permalink: /:title/